# Generated by Django 2.1.5 on 2019-02-16 23:30

from django.db import migrations, models

from examples.models import Movie, Genre


def add_genres(apps, schema_editor):
    Genre.objects.create(name='Action')
    Genre.objects.create(name='Drama')
    Genre.objects.create(name='Horror')
    Genre.objects.create(name='Sci-Fi')
    Genre.objects.create(name='Thriller')


def add_movies(apps, schema_editor):
    movie_one = Movie.objects.create(title='Inception', imdb_rating=8.8)
    movie_one.genre.add(1, 4)
    movie_two = Movie.objects.create(title='Interstellar', imdb_rating=8.6)
    movie_two.genre.add(2, 4)
    movie_three = Movie.objects.create(title='Event horizon', imdb_rating=6.7)
    movie_three.genre.add(3, 4, 5)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, null=True)),
                ('imdb_rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('genre', models.ManyToManyField(to='examples.Genre')),
            ],
        ),
        migrations.RunPython(add_genres, lambda apps, schema_editor: None),
        migrations.RunPython(add_movies, lambda apps, schema_editor: None),
    ]
